[package]
name = "lambda-lib"
version = "0.1.0"
authors = ["Dgame <rswhite4@googlemail.com>"]
edition = "2018"

[dependencies]
rusoto_core = { version = "0.43.0", default_features = false, features = ["rustls"] }
rusoto_sqs = { version = "0.42.0", default_features = false, features = ["rustls"] }
rusoto_s3 = { version = "0.42.0", default_features = false, features = ["rustls"] }
lambda_runtime = "0.2.1"
lazy_static = { version = "1.4.0", optional = true }
aws_lambda_events = "0.2.6"
serde = { version = "1.0.105", features = ["derive"] }
serde_json = "1.0.50"
flate2 = { version = "1.0.14", features = ["zlib"], default-features = false }
log = "0.4.8"
env_logger = "0.7.1"
chrono = "0.4.11"
sentry = { version = "0.18.0", optional = true, features = ["with_log", "with_panic"] }
chrono-tz = "0.5.1"

[features]
sqs = []
s3 = []
gzip = []
sentry_log = ["sentry"]
transaction_id = ["lazy_static"]
