[package]
name = "lambda-lib"
version = "0.1.0"
authors = ["Dgame <rswhite4@googlemail.com>"]
edition = "2018"

[dependencies]
rusoto_core = { version = "0.40.0", default_features = false, features = ["rustls"] }
rusoto_sqs = { version = "0.40.0", default_features = false, features = ["rustls"] }
rusoto_s3 = { version = "0.40.0", default_features = false, features = ["rustls"] }
lambda_runtime = "0.2.1"
aws_lambda_events = "0.2.5"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"
flate2 = { version = "1.0.12", features = ["zlib"], default-features = false }
log = "0.4.8"

[features]
sqs = []
s3 = []
gzip = []
